import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/products.png" type="image/png" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Hi!, Next!
        </h1>

      </main>

      <footer className={styles.footer}>
          <span className={styles.logo}>
            <Image src="/products.svg" alt="simpledoers" width={102} height={80} />
          </span>
      </footer>
    </div>
  )
}
